### ISSUE TITLE
Hotkey for 5th weapon slot and armor sets

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#104]
Add a hotkey for 5th 6th 7th (and so on) weapon slot, armor sets and armor pieces.

**Comment by HasKha** [comment]
This is not going to work as you or most people expect. Equipping items is slow and it's blocked by skill casts, so an hotkey to equip weapons or armors would be slow and clunky. I would never try to sell this as "weapon slot 5+" as it just creates expectation for something we simply cannot provide. 

That said, functionality to equip an armor would be nice, but it's not trivial, mostly because of allowing the user to select the right pieces, and for toolbox later to find them. We have to read, display and remember armor mods.

**Comment by Hour-of-the-Owl** [comment]
You can't just use the item ID of the armour pieces? o_O_o

**Comment by HasKha** [comment]
No. For example my mesmer has 4 armor sets, and several extra headpiece and parts, all of which are the same armor type, only difference being color (sometimes) and mods.

**Comment by Hour-of-the-Owl** [comment]
reporting you to the fashion police...

**Comment by reduf** [comment]
Would be too clunky.
