### ISSUE TITLE
Hide drops for others

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#105]
Hide the dark grey drops for others on the ground.
Maybe also add an option to filter certain drops out.

**Comment by HasKha** [comment]
I tried this before, back when dropping coins was a thing, to not show them and prevent fps drops. 

It's really tricky because agent creation involves several packets, and although I was somewhat successful, it was unstable. The problem is that once you stop the client from knowing about an object that is created, you have to stop all references to it or it will crash (people pinging, picking up, etc), and this requires a lot of keeping track of them.

**Comment by HasKha** [comment]
safe to say that we don't have plans to implement this, sorry
