### ISSUE TITLE
Malware, Trojan

### ISSUE THREAD

**Issue by Ruathaz** [HasKha/GWToolboxpp#113]
BitDefender which is the best protection for your computer, first prevented this download saying it was malware. Then the program was blocked because it is a Trojan. This program is used to steal your account info. DO NOT DOWNLOAD.

**Comment by Ruathaz** [comment]
If there is one way to code something, then there is another way that isn't a trojan. If you have any respect at all for the community you will either remove this program or rewrite a legitimate version.

**Comment by HasKha** [comment]
- Toolbox needs to include dll injection, x86 hooks and other techniques often used by viruses, and that's why it's sometimes detected as a virus by heuristic detection. I wish there was a way to code toolbox without the above techniques. 
- You can check virustotal scans: [dll](https://www.virustotal.com/en/file/7145ede6fa413fa544b50c2ccae2ccf018b5288d431aa1ab77f067269ce4b209/analysis/1494567474/), [launcher](https://www.virustotal.com/en/file/2ede13469382c3ce2bdade971b92411c447be1a24529ed76d4454162aeaea3cc/analysis/1494567943/). Note how the launcher is detected the most, because it downloads and injects a dll from the internet, which is scary behavior. However the launcher itself is made by very few lines of code that you can easily check.
- The code is completely open source, so you're free to look at it and try to find code to steal your account info.
- You shouldn't trust me on this, but ask any other toolbox user and you'll find out that toolbox has been around in various forms since 2014 and has never compromised anyone's account.

I respect for the community, and I've been working hard to earn and keep the community's trust for almost 4 years now.

**Comment by reduf** [comment]
*autistic screeching*

You are free to read & compile the source code although I doubt you have the capability to do it after you wrote this kind of message.
