### ISSUE TITLE
2.6 Beta

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#148]
Changes:
* Alcohol monitor is now only visible in explorable areas
* You can now once again set up hotkeys to mouse button x1 and x2 (forward and back)
* Cursor fix: the in-game cursor should not jump to your other screen any more
* User can now use multiple skills with `/useskill`, (e.g. `/useskill 134`)
* Added a Hero Builds window for loading hero teambuilds. 
* Fixed an issue where key press -> right click down -> key release would leave the key pressed on toolbox
* Added an option to show any window or widget toggle button to the main toolbox window
* Changed teambuilds storage file, now stored in `builds.ini`. Builds are now loaded when opening the window, and saved when closing the window. 

Note to testers:
**I highly recommend you backup your `GWToolbox.ini` settings first, just in case the builds are not moved properly to `builds.ini`. Please let me know if you encounter any issues**

[GWToolbox.zip](https://github.com/HasKha/GWToolboxpp/files/1610563/GWToolbox.zip)

**Comment by NetWin** [comment]
I just had a quick look into the beta and here are my results:

- **Alcohol**
✔️ only visible in explorable area

- **Mouse Hotkeys**
✔️ works in outposts with both mouse keys (tested with the load Team Hero Build Function)
❌ when triggering the hotkey in an explorable area i get a disconnect (because you cannot load a team hero build there^^)

**Use Skill**
✔️ works

- **Build Storage**
✔️ seems to work - builds get moved in the new `builds.ini` file and properly loaded 👍 

- **Herobuilds** 
✔️  Heroes get invited
✔️ Hard/Normalmode gets selected
❌ Hero and Player Builds doesn't get loaded (neither skills nor attributes)

- **window or widget toggle button**
✔️ works and i love it 👍

**Comment by HasKha** [comment]
Thanks a lot, I'll look into the issue tonight, they should be easy fixes. I'm glad the team builds worked fine.

**Comment by HasKha** [comment]
todo: reorder hero list like it is in the client (someone post the list pls)

**Comment by HasKha** [comment]
> when triggering the hotkey in an explorable area i get a disconnect (because you cannot load a team hero build there^^)

Fixed

>  Hero and Player Builds doesn't get loaded (neither skills nor attributes)

could not reproduce, works correctly for me

**Comment by NetWin** [comment]
I'll test the build loading again but it didn't work for me (maybe because i tried it with mercs and not normal heroes?)

**Comment by NetWin** [comment]
Okay my fault! i put the build in the wrong textbox 😅 
✔️ works like a charm
