### ISSUE TITLE
Clicker use, but with salvage kits

### ISSUE THREAD

**Issue by NTBugtraq** [HasKha/GWToolboxpp#164]
One very good use of an increased clicker is to salvage a stack. GWToolbox can clearly find your salvage kits, or Sup salvage kits, and apply them. Salvaging a stack of feathered caromi scales, for example. So it would require 2 options, those 2 being which type of salvage kits to use. Ideally, you would be standing next to a trader who sells the type of salvage kits you need, and could restock as needed.

**Comment by ritlew** [comment]
I think there is some sort of bot detection where if you salvage too fast it boots you to character select.

**Comment by HasKha** [comment]
thanks for pinging this. Toolbox used to contain a feature to automatically identify everything in the inventory and one to pick up items. They were eventually removed because they were not used by anyone but botters. I believe this feature falls in the same category. I want to avoid any strong correlation of toolbox with bots, so I would prefer to not implement this.
