### ISSUE TITLE
Additional Cons/Pcons

### ISSUE THREAD

**Issue by NTBugtraq** [HasKha/GWToolboxpp#167]
Why aren't pumpkin cookies, honeycombs, clovers and other DP removal/Morale boost items available in the PCONS panel?

**Comment by GregLando113** [comment]
id rather the pcons panel not span down my entire screen

**Comment by HasKha** [comment]
My reason for never implementing those is that unlike other pcons, it's not obvious what you want to do, as there are many possibilities, and toolbox might potentially fail and do harm. 

For example, you may want to:
* boost yourself to +10%
* boost morale, but without reaching +10% in order to benefit from a powerstone if one is used
* only remove death penalty

For all of those, you may want to use either party-wide or personal boosts, depending on what you are doing. 

However for speedclears you never want to use party-wide boosts, and cookies are by far the best and most widespread pcon used. Why? They allow non-random control over your own morale only, allowing you to go to positive morale without reaching +10, and they are cheap and easily available. 

The typical use case is dying (-15%), using two cookies for +20% -> +5% morale, and now you have more hp/energy while still being able to use a pstone. 

If you automate this process, it can happen that toolbox detects death penalty and uses a cookie, *at the same time* as mobs are dying. The server will process mob death, give you experience thus removing DP, and then applying the cookie, thus resulting in +10% morale, which is really bad for some SCs.

So overall I always decided against implementing this feature.
