### ISSUE TITLE
put full stacks in the trade window

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#190]
When I drag a stack of anything into the trade window, I do not wish to be asked how many - the answer is almost always "all of them". Please make this default behaviour: skip the question of how many and just put the whole stack in there.

Perhaps make it so holding down Shift represses this, giving the standard and expected behaviour of offering to split the stack. Never mind if that's too much hassle though - if I want to put in less, I can split it beforehand, NP.

The same is true for dropping items on the floor, although that fix might be primarily beneficial for botters, so maybe you don't want to do that one.

Maybe someone who lives in Kamadan has a stronger opinion about this, but I suspect there are no TB users who would dislike this feature. If I'm correct, there's no need to include an option to turn it off.

**Comment by HasKha** [comment]
sounds like a good idea, however a few notes:
* I don't know how to actually do this. I don't think we have on-item-transfer hooks yet, so it requires some low level work
* Changing the default behavior of a sensitive action like trading or dropping is bad because some user may feel like I am trying to scam them (they are used to trade 1 and might end up trading many without noticing), so this will have to be an optional feature, defaulted off.

**Comment by tjubutsi** [comment]
What about, if trade window is open, ctrl click adds item to trade window instead of to storage?
