### ISSUE TITLE
Cursor offset in borderless mode

### ISSUE THREAD

**Issue by disteLLL** [HasKha/GWToolboxpp#200]
While in borderless the cursor is actually a bit lower than displayed. I can fix it by restarting Toolbox a couple of times, but it happens always on the first start. Might be a problem on my end since I had this issue for quite a while now, but I'm out of ideas what causes this.

Update: Whenever I check "Borderless Window", I get "Already in Borderless mode" in chat. Don't know if that's an indicator on what's going wrong.

**Comment by reduf** [comment]
Do you have a taskbar or you let Gw take the full screen ?

**Comment by disteLLL** [comment]
What do you mean by that? Borderless works only when Gw is in windowed mode.

**Comment by Sognus** [comment]
I also have similar issues. Sometimes when I start Toolbox without character selected while I am in windowed mode, game cursor location is fine, but Toolbox's real location is slightly more up+left (towards 0,0 - if 0,0 is top left corner). 

I can't really provide screen because it happens rarely. When it happens again I will update this with screen. Issues is just when u have button (for example: Settings one), it has different area that reacting to click than one rendered (simply: On bottom side of button it does not read mouse click, slightly above button [outside rendered button] it reads that click.

I did not detect this issue when I started GWTB++ after I logged on some character. I tried to use both with and without automatic hiding of main panel (is it called taskbar in EN?). It looked like it was happening with automatic hide more than without.

**Comment by HasKha** [comment]
when this happens does it affect just toolbox or gw as well?

**Comment by Sognus** [comment]
As for my issue: Game UI seemed to be fine. It was most likely only issue of Toolbox's GUI - render vs real positions. I can't tell for sure tho, as I said it only happened sometimes, not all times, I haven't seen it for a few days. 

Note: I haven't seen it in TB's older version, all sights of this behaviour was on 2.10

**Comment by disteLLL** [comment]
For me both is affected. It seems like it stretches the window visually but the actual positions of everything stay the same.

**Comment by reduf** [comment]
Borderless was officially added to the game [here](https://wiki.guildwars.com/wiki/Feedback:Game_updates/20180509) so we don't support it anymore.
