### ISSUE TITLE
Add capability to save and load GW UI layout

### ISSUE THREAD

**Issue by HasKha** [HasKha/GWToolboxpp#225]
useful for sharing accounts and pcs. 

note to devs: can be done by hooking/faking layout settings packet

**Comment by Hour-of-the-Owl** [comment]
might also be nice to get all the settings; not just the interface

**Comment by Bu11etmagnet** [comment]
This would be neat (I have many accounts and the UI is different for each), but I often run the same account on different monitors with different resolutions. How would that work?

**Comment by reduf** [comment]
Here is few details about this feature.

Firstly, many (if not all) of the settings are sent with the interface if I remember correctly. So, this feature would cover both of those. The most convenient implementation is that all settings are saved in a profile. (i.e. We don't make additional parsing such as "don't ovewrite this list of settings")

Second, regarding how it would work on different resolutions. We would be completely agnostic to that. The behavior of loading a setting on screen 2 that was saved on screen 1 would be exactly the same as going on screen 2 after playing on screen 1. But, you could save a profile per screen and load them accordingly.

Regarding the difficulties: Although we found were the blob is and we can kind of understand how to deal with it, there is few problems. I don't feel very confident to just feed the data without understanding the format, because that is a easy way to create crashes. The way this data is require some efforts to reverse, because there is a lot of trial and error. Furthermore, if we don't know the format, it won't be very robust against updates.
