### ISSUE TITLE
Add a button combination to put items directly into the trade window

### ISSUE THREAD

**Issue by D4v3-D** [HasKha/GWToolboxpp#230]
Just like Ctrl+LMB puts it in the Xunlai Chest a button combination to put items directly into the trade window if it is open would be very nice.

**Comment by 3vcloud** [comment]
Because ctrl + click is commonly used in TB to move items to/from storage, it would be too confusing to do that. I've gone for double-click to move from inventory to trade window when its open, because you can already double click an item that is in the trade window to remove it so makes sense to do vice versa.

I've also put in some logic to make moving items to trade window the same as moving items elsewhere in the game i.e. if you drag the item it will add the whole stack, but if you drag and drop whilst holding shift it'll ask you for quantity.

Next release, https://github.com/HasKha/GWToolboxpp/commits/8bc197dc8e1f5ed997a0d54dc0883107ac7d9719
