### ISSUE TITLE
Some Hero Bugs/Suggestions

### ISSUE THREAD

**Issue by PhilohGW** [HasKha/GWToolboxpp#238]
1. minimap/hero flags are bugged in Urgoz Deep (i asume due to more then 7 heros (i playerd with some1 else, i got 7 heros he got 3))
![unbenannt](https://user-images.githubusercontent.com/32037794/42490409-54d0eb7a-8410-11e8-8d2b-2a5c936ecdd5.png)
2. i once (and never was actually able to reproduce it) that i had (as sin/warr) had the SoH (Monk Bond) from one of my heros in the Bond monitor. I was able to take the Bond down (deactivate it), but not to activate/put it up again. I asume some bug - and as i said had it once - never again.
3. some times, if i use my HeroBuild Hotkay, the builds will not get Loaded, it takes the right heros into PT, but actually does not load the build.
4. A suggestion; would it be able to "set" your herobuild up, like put some Heros on "aggresive"/"normal"/passive" or, e.g. block a special Skill? every time (if not "3." happens^^) i need to block SoH from my SoS manual, would be a plessure, if it would happen automatikly^^.but i know its "alot of work" for .. actually not really a big issue tho..

**Comment by HasKha** [comment]
As a general note, in the future please open an issue for each item, as it makes it easier to keep track of them, discuss, implement, and close.

1. Added to #61 
2. Weird, somehow the game thought you generated the bond, rather than your hero. Might be related to #235, but without reproduction steps I cannot do much (and it's not critical to justify serious debugging).
3. I would suspect it is some timing issue (trying to load the build before the hero is actually added). Need investigation.
4. I don't know if we have this in GWCA++, but it's a good suggestion.

**Comment by reduf** [comment]
I created an issue for number 4, the other points should be fixed.
