### ISSUE TITLE
Alcohol Pcon

### ISSUE THREAD

**Issue by soulninja777** [HasKha/GWToolboxpp#255]
Hello, not a problem per se...but im noticing my pcons function is not seeing my "Kegs of Dwarven Ale"
Item ID for Keg is 31146 if that helps, i just cant figure out how to fix it on my own XD

**Comment by soulninja777** [comment]
nvm...i guess it does see it but it registers as a really low number (which is weird, i thought kegs were "strong" ale)?

**Comment by HasKha** [comment]
this is where alcohol quantity is counted: https://github.com/HasKha/GWToolboxpp/blob/master/GWToolbox/GWToolbox/Windows/Pcons.cpp#L272

kegs are 1 item. the usage count is a separate attribute of the item. Right now each keg counts for 5 minutes of alcohol regardless of its usage count, so the toolbox counter is off, but they will still be used correctly. In theory we could check for it in the above function, but it was always very low priority because the usage is still correct, and kegs are overall a terrible item for SCs: they cause alcohol emotes, and can only store 50 uses per inventory slot, as opposed to other items that can stack up to 250.

I'm going to mark this as wontfix since its super low priority, but feel free to implement it and make a pull request.
