### ISSUE TITLE
remove dead Imperial Guards from party window's allies list

### ISSUE THREAD

**Issue by smiley232** [HasKha/GWToolboxpp#272]
Would it be possible to remove the dead imperial guards spawned by the Imperial Guard Reinforcement Orders from the party window? The party window can get pretty confusing when some stones were popped and you have to watch allies, for example.
Thanks.

**Comment by HasKha** [comment]
I guess you mean any dead summoning stone? Or is there any specific reason for Imperial Guards?

Anyway, this might be trickier than it seems, because not only we need to make the client hide them, but also make sure that nothing references those, and the client doesn't crash when the server eventually decides that it's time to hide them.

**Comment by HiImFlo** [comment]
Its specific for imperial guards, they dont disappear from the group window at all.

**Comment by HasKha** [comment]
TIL. This feels like one of the easy fixes the devs should implement. It should be easy for them and hard for us, but we'll see.

**Comment by reduf** [comment]
> devs should implement

about that
