### ISSUE TITLE
Hero build tool suggestions

### ISSUE THREAD

**Issue by Bu11etmagnet** [HasKha/GWToolboxpp#274]
There are two things I'd like to see:

- Ability to set some skills to disabled (what Shift-click does). I have a team build for running ATFH, but half of the heroes' skills need to be disabled. I ended up not using the toolbox hero build window, because it's quicker to manually add the heroes (who already have the builds with the appropriate ones disabled) than loading the team build and then shift-clicking a dozen skills.
- Ability to turn on the hero control panels. I like to keep an eye on my heroes.

**Comment by HasKha** [comment]
Overall those are good ideas that should be nice to have. Just a few implementation notes:
* The first one is a bit painful for the UI, since it basically involves 8 checkboxes, in an already packed window. 
* Both features require functionality not currently present in the API (gwca), namely disabling hero skills, and opening hero control panels. Those will need to be added to make this possible.

**Comment by Bu11etmagnet** [comment]
Actually, half of what I want (add heroes with the build they had last) is already there. Just leave the template field empty.
Turning on hero control panels would still be nice.

**Comment by jnvsor** [comment]
+1 for opening control panels

**Comment by 3vcloud** [comment]
Added in 4.2
