### ISSUE TITLE
Spiritual Possession breaks alcohol timer

### ISSUE THREAD

**Issue by 3vcloud** [HasKha/GWToolboxpp#302]
Once a player has spiritual possession, the PostProcess hook is updated constantly every few seconds with a level of 5. This will stop alcohol pcon from working.

**Comment by 3vcloud** [comment]
Is there any way to hook into a packet that updates the drunkard title instead of relying on post processing?

**Comment by reduf** [comment]
Alcohol is very annoying, because the algorithm used is very strange. In fact, it's not so suprising, because it's the only effect that persist cross server which, I guess, creates some problems. That's also why I didn't implement the alcohol timer. (i.e. it was too unreliable)

You can test, by using a charge of alcohol or two, then change zone (or provoke other edge cases) and observe the timers or when the ppe level goes down.

Assuming that we can reproduce that algorithm, we could then hook the alcohol usage and be more accurate.

**Comment by HasKha** [comment]
linking discussion to https://github.com/HasKha/GWToolboxpp/pull/303
