### ISSUE TITLE
Enter mission hotkey

### ISSUE THREAD

**Issue by HiImFlo** [HasKha/GWToolboxpp#322]
Basically title. Add the option to create a hotkey to start the current mission from the outpost. Would probably fit best into the "Execute..." category.

Maybe make it a start/cancel button, so when activiating it while the countdown is going it cancels it.

**Comment by 3vcloud** [comment]
I don't really understand why you would want this instead of pressing the enter mission button in the party window?

If you're talking about missions including the ones where you have to talk to an NPC, thats not possible without automating the character's movement and actions which would raise some issues in itself.

**Comment by HiImFlo** [comment]
Because pressing the button is annoying, simple as that.

No, I am just talking about the mission that have such a button, as in Urgoz, Deep, Factions and Proph missions.
