### ISSUE TITLE
can't run GWToolboxpp

### ISSUE THREAD

**Issue by bluelovers** [HasKha/GWToolboxpp#323]
![image](https://user-images.githubusercontent.com/167966/54876050-50b08880-4e44-11e9-823b-2523a48b0515.png)

![image](https://user-images.githubusercontent.com/167966/54876052-54dca600-4e44-11e9-9e0a-5fd45b6870b0.png)

i also try download dll but still fail
https://github.com/HasKha/GWToolboxpp/releases

![image](https://user-images.githubusercontent.com/167966/54876058-645bef00-4e44-11e9-99b4-17af45000994.png)

**Comment by reduf** [comment]
Hey, I will copy our troubleshoot message from Discord, because it's generally enough to fix all the problems related to launching toolbox. Let us know if it fix it or not.

Sorry to hear that GWToolbox is not working for you. Here are some basic steps to try and get toolbox to work.

 - Make sure you are running GWToolbox.exe as administrator.
 - Make sure the Visual C++ 2015 Redistributable (vcredist_x86) is installed on your machine. (https://www.microsoft.com/en-us/download/details.aspx?id=48145)
 - Make sure the DirectX Runtime is installed on your machine. (https://www.microsoft.com/en-us/download/details.aspx?id=35)
 - Make sure Data Execution Prevention is not interfering with GWToolbox. See https://www.online-tech-tips.com/windows-xp/disable-turn-off-dep-windows/.
 - Make sure your anti-virus is not interfering with GWToolbox, make an exception for GWToolbox.exe to allow it to run without issues.
 - Go to your GWToolbox folder by using %LOCALAPPDATA%\GWToolboxpp in a Run command window (Windows Key + R). Is there a GWToolbox.dll? a Font.tff? is there an img folder?
 - If there is no GWToolbox.dll, download the latest dll from https://github.com/HasKha/GWToolboxpp/releases, and put it in the GWToolbox folder, retry launching.
 - If Toolbox still does not load, try launching the toolbox using https://cdn.discordapp.com/attachments/224695376102293514/429812366033682433/Inject.exe, by putting this program in the Toolbox folder, and running as Administrator.
 - If you are updating from the March 23rd update, please see !2.9.

 Please try the above reccomendations before asking for help. If none of the above is helping you run GWToolbox, please let a developer know.
