### ISSUE TITLE
cooldown timer

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#37]
on GW2 you can have it show how many seconds are left on your cooldowns and effects - can we have a thing like that? maybe showing tenths of a second, or maybe not

**Comment by HasKha** [comment]
this is difficult. I'll leave it here, but it would be a long term project.

**Comment by HasKha** [comment]
example implementation from #241: 

![tb](https://user-images.githubusercontent.com/35411980/43450095-3f17ed08-94b2-11e8-87db-67686bcb850d.png)

**Comment by HasKha** [comment]
A few thoughts:

Detecting skill CDs is really easy, the problem is visualization. We have not explored the in-game UI, and don't know where the skillbar is. This would require some investigation. In the screenshot above, it is possible the author had a fixed location for his UI.

I watched him play a bit on stream, and honestly I don't like the feature, at least not presented like that. The numbers add a lot of noise and generally reduce the clarity of skill CDs, rather than improve it. As a player, seeing my skills halfway recharged or 3.8s until available makes no difference in how I play. On the other hand, I do see value in communicating skill CDs, for which having a visible counter is useful ("make haste in 7", "shadow form in 10", etc). For that, I would look at how League does it, and have a small non-intrusive number without decimals.

**Comment by 3vcloud** [comment]
Added  > 4.0
