### ISSUE TITLE
Toolbox issue with multiple acounts

### ISSUE THREAD

**Issue by jc25701** [HasKha/GWToolboxpp#394]
if you are running multiple clients toolbox will not load. used to it would ask which account  now it just shows  in the taskbar  script paused

**Comment by BearsMan** [comment]
u cant run Toolbox standalone on 2 accounts because the script will only allow up to 1 account per use unless u are using GW Launcher with GWToolbox.dll inside GW Launcher folder which will allow the script to remain active regardless of which account u are using, look into @GregLando113 GW Launcher page shown here: https://github.com/GregLando113/gwlauncher/releases

**Comment by reduf** [comment]
You need to update the launcher here: https://github.com/HasKha/GWToolboxpp/releases/download/2.29_Release/GWToolbox.exe
