### ISSUE TITLE
opening toolbox while dead and spectating someone

### ISSUE THREAD

**Issue by ExcrementSniffer** [HasKha/GWToolboxpp#45]
Nothing major!
Just noticed if you run toolbox while you're dead and have another party member selected thats alive it comes up with their name instead of your own... (Doesn't include hero's & henchies)

**Comment by HasKha** [comment]
Never thought about it, but yes, it is to be expected. Spectating a party member while dead internally shows as if you _were_ that player. The major side-effect is that toolbox will typically try to use pcons (since it sees the player alive and no pcon buffs), but luckily it's not an issue. 

Anyway, unless someone finds a way to detect when gw is spectating a party member, this won't be fixed.

**Comment by HasKha** [comment]
Update on this: toolbox will now recognize when it's spectating someone and not try to use pcons, but that only works if it's been active since you zoned, so it won't help with the original issue, which won't be fixed.
