### ISSUE TITLE
Fix travel from factions to elite areas

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#47]
As the title says.

**Comment by Hour-of-the-Owl** [comment]
Unless there's some 1337 h4x0r5 way to do this, the obvious workaround is:
Whenever you try to TB map to an elite area, do a quick check if you're in a Factions map.
If yes, instead map to some pre-determined outpost that won't fail, and then map from there to your destination.

I think the only real question is which outpost? What's the one non-Factions outpost people are most likely to have if they want to travel to an elite area? GToB or Embark, surely, although neither of them is 100% guaranteed. To be fair though, I don't think people who make a Factions character and get it to Urgoz/Deep without going to KC really DESERVE to use travel functions...

**Comment by HasKha** [comment]
Honestly I have no idea about the cause of this issue and don't even know where to start to fix it. I'm hesitant at implementing a work-around, because double-travel is tricky (travel too slow and it's bad, travel too fast and you may crash or lose party members). Best would be to fix it, but I'm afraid we'll just have to live with this one, going gh and then travelling anywhere is not *that* bad.

**Comment by reduf** [comment]
No good fixes & it's Anet fault :)
