### ISSUE TITLE
Ctrl+click to withdraw from mats pane

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [HasKha/GWToolboxpp#486]
Is there a particular reason I can't withdraw from the materials pane with Ctrl+click? It seems like that's how it should work.

**Comment by 3vcloud** [comment]
its easy to create hooks for things that the game is already using for player interaction, which is why item clicking in the normal panes works - we just hook into the function that allows you to use cons or kits straight from the chest and its all good. The material pane doesn't have the same behaviour, so its trickier to get it done

**Comment by 3vcloud** [comment]
Next release, https://github.com/HasKha/GWToolboxpp/commit/2a9bb4a8cab7787b220cbf45567a706462362499
