### ISSUE TITLE
Adjustable size of all widgets

### ISSUE THREAD

**Issue by DubbleClick** [HasKha/GWToolboxpp#506]
Playing on 1080p feels so cluttered given that all TB widgets are very large. It would be cool to have the option to scale all of them in size, resulting in this neat experience:
![image](https://user-images.githubusercontent.com/7896469/90430443-b94a7600-e0c7-11ea-87c3-c3579f26b178.png)

**Comment by HasKha** [comment]
Currently there is an option for global font scaling, and you can resize all the other elements of the UI. That said, there will be a limit where things and fonts don't render as nicely, just because of pixel density. 

Global scaling of the UI won't work well, as it would mess up pixel alignment of UI elements, and ruin font rendering. 

One possible improvement would be proper support for user-specified font sizes.

**Comment by 3vcloud** [comment]
Unless ImGui has addressed the issue with font sizes, the only way to do it is pre-load the fonts in different scales as we're already doing, and apply font scaling on the closest upper font size - would still look dodgy because of the scaling

**Comment by HasKha** [comment]
yea, but we could allow user control on those loaded font sizes. It will require to relaunch toolbox, but it's the best we can do.

**Comment by DubbleClick** [comment]
Not sure how well it plays together with ImGui, but couldn't we also transform the render target to something smaller? I have no idea so this might sound ridiculous

**Comment by HasKha** [comment]
> Not sure how well it plays together with ImGui, but couldn't we also transform the render target to something smaller, similar to how the minimap is scaled? I have no idea so this might sound ridiculous.

Unfortunately this will make a lot of things look really bad. Mostly because of font rendering and pixel alignment of straight lines.
