### ISSUE TITLE
Widget for the Xunlai Chest

### ISSUE THREAD

**Issue by DarkManic** [HasKha/GWToolboxpp#53]
Add a widget with a button to open the Xunlai Chest. The widget should only be visible in outposts. Something like the widgets you can drag out of the regular Guild Wars menu.

**Comment by HasKha** [comment]
I like the concept, but I cannot image this being used by many, since /chest and open chest hotkeys exist, so I cannot really justify taking a slot in settings / info for this. 

Ideally this would be exactly the kind of feature the future modular system is for, where you can create and share your own functionality. 

That said, if we would take too long to get there, we may want to add this in some alternative way.

**Comment by Bu11etmagnet** [comment]
Open Xunlai Chest and Borderless Window are the two features I use most often. It would be nice if they were accessible with one click.
