### ISSUE TITLE
DoA Objective Timer (New)

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#564]
I think I made have found a bug in the timer while doing DoA I noticed that Outside City, 4 Lords and Underlords did not show when it was completed, I will post screenshots here: https://i.imgur.com/y0AHIWN.jpeg and https://i.imgur.com/58jVZKA.jpg

thank u 

Bears

**Comment by HasKha** [comment]
By the way, you can attach images to the github thread directly.

1) The DoA city outside is triggered by the door opening. It works fine for me. Since it's a city start, my guess is that you loaded slowly, and someone took the quest (and opened the gate) before you zoned in. I could just change it start with city, but I'm not sure I want to. 

2) you weren't in range to see 360 start or underlords finish/lord start. Those use the veil gates opening.

**Comment by BearsMan** [comment]
I'll close the issue since fixed in 4.5 update
