### ISSUE TITLE
Installer doesn't give - or ask for - any information.

### ISSUE THREAD

**Issue by kassimir** [HasKha/GWToolboxpp#574]
I just downloaded the installer, and it said GWToolbox wasn't installed. I clicked to install it. It didn't tell me where it was installing, and off it went. It then popped up to tell me "Failed to inject GWToolbox into Guild Wars." Probably because it never asked me where my Guild Wars is located. I have 5 drives on my computer, so the odds that it would find the right one on its own are pretty slim. And now I can't do anything at all, because whenever I click the installer, it simply tells me it failed. I was pretty excited to try this out, but I guess that won't be happening.

**Comment by reduf** [comment]
It's installed in `%localappdata%\GWToolboxpp\`, but we don't need to know where Guild Wars is installed, because Guild Wars needs to be running. That might be the reason why you had the error.

I'm somewhat surprised it says "Failed to inject GWToolbox into Guild Wars.", because I believe the current launcher would say that no instance of the game were found and asked if you want to restart as admin. Maybe you are running a older version of the launcher, but first try to just start Guild Wars, connect and start playing a character before running GWToolbox.exe.
