### ISSUE TITLE
4.8 Update - Useskill for single skills not really usefull

### ISSUE THREAD

**Issue by mikro1st** [HasKha/GWToolboxpp#576]
I like and use your tool a lot. :)
However, since 4.8 the useskill function is not helpfull anymore, so i needed to downgrade the toolbox to 4.6 (because the 4.7.1 link in the history md doesn't work)
Hopefully you do either fix the issue you had with multiple skills or bring the feature in some other way back. :)

Never the less! Great job so far, i really appreciate your effort you are putting in here!

**Comment by BearsMan** [comment]
I highly doubt it will come back because from what I believe using the skill chain can be related to the game thinking u are botting if going afk for any reason but that's just what I think it is

**Comment by 3vcloud** [comment]
Yep, chaining multiple skills without user input has been intentionally removed. What was your use case for `/useskill` before this?

**Comment by mikro1st** [comment]
Most of the time I play GuildWars with old guild collegue, we are both dads since a few years, so it meight occure that we need to react fast in real life sometimes :D  
so... beeing afk for short, but with the will to stay alive, for example :D (at least holding sf and sod up is really helpful)
furthermore, we also use /useskill for an additional emo bonder on a secundary account, was also usefull to keep the enchantments up while spamming 1

**Comment by 3vcloud** [comment]
Ok yep, these points were brought up when we were deciding how to handle this, and ultimately came down to where to draw the line between improving gameplay and automating it. Theres a few things that I considered when changing this:

1. GWToolbox is a tool to improve your play experience, not play for you. Whilst things like popping pcons could be argued, we're pretty certain that using a pre-defined set of skills on your skillbar based on recharge and energy management is pretty much playing for you. This includes maintaining enchantments on emo.

2. The original use case for this was using Dhuum's rest because it takes a million years to do it so people wanted to be able to use that single skill without growing old and dying of boredom, but these days its also being used to maintain single shouts for HR paragon, and single e-management skill for emo.

3. How to prevent players being able to exploit this tool by not actually having to play the game, i.e. botting

Honestly I wanted to do away with this feature altogether, but because the dhuum thing was such an issue this was instead limited to 1 skill and still allowed some limited level of automation:

1. As an emo you can skill spam your e-management skill with it, but it means you have to engage with the game to maintain enchantments as intended.

2. As a HR paragon you can spam your upkeep shout as before

3. As a perma you can maintain SF but will just have to position yourself somewhere where you dont receive physical damage.


This ticked most of the boxes and kept it away from being taken advantage of. If you need to automate gameplay any more than this, then TB isn't the tool to do it.

**Comment by mikro1st** [comment]
Thanks for the honest and detailed answer :) I think with that we can close the Issue.
