### ISSUE TITLE
Observer Mode: Change ordering of skills

### ISSUE THREAD

**Issue by NickGw99** [HasKha/GWToolboxpp#588]
## Problem:
Skills are currently ordered by skill_id. This is makes skill bars look confusing.

See:

https://github.com/HasKha/GWToolboxpp/blob/cc77581266f3abd40cfe6081a9decd0961d994c3/GWToolboxdll/Modules/ObserverModule.h#L315

## Solution:
**Sort by function** instead of skill_id.
Figure out and implement some heuristic for to sort by function.

For example:

- attack skills
  - lead -> offhand -> dual
- shouts
- stances
- signets
- any remaining non-spell skills (?)
- non-enchantment spells
- enchantment spells
- rezzes
- anything that was missed

**Comment by 3vcloud** [comment]
Function is too complicated. Async decode the skill name, then reorder once you've got it

**Comment by 3vcloud** [comment]
Sorry, **ordering by function** is too complicated, and a user would expect it to be alpha order anyway on-screen. Queue a decode of the skill name, and then check it in the update loop and reorder it when you've decoded the name.

A note regarding the use of references; I'm not sure what this would do with a map or vector that gets resized or re-ordered, and you're mixing pointers with references in your function calls. I'd suggest sticking to pointers because you have full control over when these objects are freed or moved.

Also, try to keep most of your function definitions in the source (cpp) file, and only the declarations in the header file

**Comment by NickGw99** [comment]
> Sorry, **ordering by function** is too complicated, and a user would expect it to be alpha order anyway on-screen. Queue a decode of the skill name, and then check it in the update loop and reorder it when you've decoded the name.

Fair enough. Ordering by name would be much easier. My main motivation for ordering was when uploading exported matches to [gwrank](https://gwrank.com) the skill bars were looking funky, but I've just spoken to Arka from gwrank again and he has workarounds for it.

> A note regarding the use of references; I'm not sure what this would do with a map or vector that gets resized or re-ordered, and you're mixing pointers with references in your function calls. I'd suggest sticking to pointers because you have full control over when these objects are freed or moved.

Noted :+1: . Happy to stick with pointers. Is there a convention to signal a pointer type (for example as an function argument or return value) must be non-nullable? I was naively requiring reference arguments or returning references to signal non-nullability. Will fix on my next PR.

> Also, try to keep most of your function definitions in the source (cpp) file, and only the declarations in the header file

Also noted :+1:. Will fix on my next PR.
