### ISSUE TITLE
GW Hotkey option doesnt work when entering an area

### ISSUE THREAD

**Issue by Marco3104** [HasKha/GWToolboxpp#661]
When useing the Hotkey "Guild Wars Key" with the option "Trigger hotkey when entering explorable area" doesnt work. 

I tested: "Targeting: self" and "Action: Order Hero 6 to use skill 8"

When i enter an explorable area i neither targed myself or my hero 6 useing skill 8. (Targeting self also doesnt work when useing the option "Trigger hotkey when entering outpost".

**Comment by 3vcloud** [comment]
So the way the GW UI works is easy window or "frame" is created after map map itself has loaded. Part of that creation is to subscribe to an action and do something when that action is taken.

The user interaction is initialised by the game at a later time, and TB doesn't know exactly when or how its triggered, so doesn't know how to trigger the "GW" hotkey on load (it does actually try to trigger it, but because the action hasn't been "subscribed" to yet, it does nothing)

For this reason, triggering this type of hotkey on map load will be removed as an option, because it isn't ever going to work
