### ISSUE TITLE
Please add Aggressive Refrain to Bonds

### ISSUE THREAD

**Issue by apathyward** [HasKha/GWToolboxpp#884]
All the other Refrains got added, but this is the one everyone is using.

**Comment by DubbleClick** [comment]
I really don't think anyone is using this, but sure, it's added.

**Comment by RiftLurker** [comment]
I don't think adding Aggressive Refrain adds any value here as you can only use it on yourself. This is why I originally left it out, alongside similar skills like Critical Agility or Mental Block, you can just look at your effect monitor for those.
If there is an actual desire to monitor your heroes [self casted skills with renewal effect](https://wiki.guildwars.com/wiki/Renewal_effect), please handle them separately.

**Comment by 3vcloud** [comment]
I think because of where the widget is, its useful to keep an eye on the whole party including yourself without looking elsewhere (looking at you, toolbox minimap)

**Comment by RiftLurker** [comment]
Self casted skills are easily tracked on your own effect monitor or with the skillbar widget and I would trust heroes to maintain them on themselves as much as you want. I wouldn't want to sacrifice an entire column in my bond monitor just because I like to bring Aggressive Refrain on my HR Paragon, it's taking away from more important refrains. 
If you want to add all the current bonds/refrains to the bond monitor, even if it's only on a heroes skillbar, that's something I can get behind with (although preferably as an option).

**Comment by Hour-of-the-Owl** [comment]
please consider removing this koz it's annoying (=
