### ISSUE TITLE
Crash on 6.7 

### ISSUE THREAD

**Issue by BearsMan** [HasKha/GWToolboxpp#896]
I did a stream of this run here: https://www.twitch.tv/videos/1808853242 - crashed at 4:45 with a dialog pop up

 
[6.7-20230501-150935-32612-9496.zip](https://github.com/HasKha/GWToolboxpp/files/11367600/6.7-20230501-150935-32612-9496.zip) (crashed during ZB (Kanaxi - The Deep));

I know it popped up because I checked in Task Manager too.

it may not needed but it does not hurt to check before 6.8 release

**Comment by BearsMan** [comment]
It may not be needed but just in case.

**Comment by 3vcloud** [comment]
I took the time to look at this crash dump, and its nothing to do with toolbox - looks like either a rendering issue loading the resource for an in-game model, or an **in game texture** that was mis-loaded.

If you get a crash without using texmod, let me know, otherwise I won't look at any other dumps from your 6.7

**Comment by BearsMan** [comment]
Okay, sounds good. I'll keep an eye out.

**Comment by BearsMan** [comment]
I know we closed this but I fixed it, even the auto-crash. It was an issue with in-game textures loading incorrectly.
