### ISSUE TITLE
Feature Request: Extended Friends List

### ISSUE THREAD

**Issue by JimIrsay** [HasKha/GWToolboxpp#908]
Is there anything you can do to make the friends list longer? Like a hotkey that brings up a new friends list?

**Comment by Hour-of-the-Owl** [comment]
You could easily store a list of character names, and then couldn't you just periodically check if they're online? It wouldn't _instantly_ notify you when someone logs on, but otherwise I think the only missing feature would be displaying the location of "mutual" friends.

**Comment by 3vcloud** [comment]
No, the main point of this is that the friend list is too long, meaning there isn’t any more space to periodically add a friend to check, and I’m not going to kick a legitimate person from the friend list to do that because then it gets messy figuring out who’s a toolbox friend and who isn’t.

I wrote the code for this 3 years ago for the friend list module and had so many stability issues that the module turned into a widget to show an overlay for your normal friend list.

**Comment by JimIrsay** [comment]
So you're saying there's a chance? What's the monetary cost/value behind
adding a stable addition? I hate having to remove people or having a 2nd
account to do it.

**Comment by DubbleClick** [comment]
No, there's no way to actually extend the real friend list in the game.

**Comment by JimIrsay** [comment]
You could easily store a list of character names, and then couldn't you
just periodically check if they're online? Guess you don't want money
either. Guess I'll just make it myself.

**Comment by DubbleClick** [comment]
You're come to try, but it'll be a buggy mess thanks to the actual bugs surrounding the friend list of the game.

Not to mention, if your friend didn't have you on their permanent friendlist but also only periodically checked, you wouldn't get his location. And there are likely other issues surrounding this approach that I haven't even thought about.

**Comment by JimIrsay** [comment]
Yeah i don't need their location. Just to see if they are online. Seems
like a reasonable ask, I even offered to compensate if that wasn't clear.

**Comment by DubbleClick** [comment]
It's not unpaid time commitment that keeps us from implementing this, it's the instability and bugginess of the in game friend list system.

The only way this could be reliably implemented is through creating a listener/publisher approach with our own servers specifically for toolbox users. But then there are security implications.

**Comment by 3vcloud** [comment]
The code that makes up the friend list window module on toolbox is actually pretty monolithic for something as simple as an in game overlay. That’s because I put a lot of time into trying to do exactly what you and others are asking, came up against limitations and issues, and instead of deleting the code I left it in for reference. It’s a bit messy because I wrote it a long time ago, but if you want to try yourself it could be a good starting point.

Regardless, to reiterate, it’s not possible to implement with any reasonable amount of stability otherwise it would have been done years ago already
